/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import picocli.CommandLine;


public class App{
    public void run(Cli c){
        if(c.format == Format.Json){
            System.out.println("OK");
        }
    }
    public static void main(String[] args) {
        int exitCode = new CommandLine(new Cli()).execute(args);
        System.exit(exitCode);
    }
}
