/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import picocli.CommandLine;
import example.Cli;

public class App {
    public static void main(String[] args) {
        int exitCode = new CommandLine(new Cli()).execute(args);
        System.exit(exitCode);
    }
}
